/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2015-11-30 10:41:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import javax.sql.*;
import java.sql.*;
import java.awt.*;
import java.io.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("  \n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<style>\n");
      out.write("body{\n");
      out.write("color:\"white\";\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<style type=\"text/css\" media=\"screen\">\n");
      out.write("            #carbonads {\n");
      out.write("              padding: 20px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            #carbonads .carbon-img {\n");
      out.write("              clear: both;\n");
      out.write("              float: left;\n");
      out.write("              background: #fff;\n");
      out.write("              padding: 10px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            #carbonads .carbon-img img {\n");
      out.write("              display: block;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            #carbonads .carbon-text {\n");
      out.write("              clear: both;\n");
      out.write("              display: block;\n");
      out.write("              padding: 10px 0;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            #carbonads .carbon-poweredby {\n");
      out.write("              display: block;\n");
      out.write("              color: #ADB0BA;\n");
      out.write("              font-size: .9em;\n");
      out.write("            }\n");
      out.write("          </style>\n");
      out.write("\n");
      out.write("    <title> MCELLBLOCKS</title>\n");
      out.write("    <!--REQUIRED STYLE SHEETS-->\n");
      out.write("    <!-- BOOTSTRAP CORE STYLE CSS -->\n");
      out.write("    <link href=\"assets/css/bootstrap.css\" rel=\"stylesheet\" />\n");
      out.write("    <!-- FONTAWESOME STYLE CSS -->\n");
      out.write("    <link href=\"assets/css/font-awesome.min.css\" rel=\"stylesheet\" />\n");
      out.write("   <!--  ANIMATED FONTAWESOME STYLE CSS -->\n");
      out.write("    <!-- <link href=\"assets/css/font-awesome-animation.css\" rel=\"stylesheet\" />  -->\n");
      out.write("     <link href=\"css/session.css\" rel=\"stylesheet\" /> \n");
      out.write("    <link href=\"css/elusive-webfont.css\" rel=\"stylesheet\" />\n");
      out.write("    <link href=\"css/pages.css\" rel=\"stylesheet\" />\n");
      out.write("    <link href=\"css/sunburst.css\" rel=\"stylesheet\" />\n");
      out.write("       <!-- CUSTOM STYLE CSS -->\n");
      out.write("    <!-- <link href=\"assets/css/style.css\" rel=\"stylesheet\" /> -->\n");
      out.write("    <!-- GOOGLE FONT -->\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    \n");
      out.write("      <div class=\"contentWrap\">\n");
      out.write("        <div id=\"content\">\n");
      out.write("          <header>\n");
      out.write("          <h1><img src=\"img/bootstrap/mobile-integration-workgroup-squarelogo.png\" border=\"0\" alt=\"MIW\" style=\"margin-bottom:'0px';height:80px;width:'80px;'\"/></h1>\n");
      out.write("            <ul class=\"commonNav\" id=\"main-nav\">\n");
      out.write("            \n");
      out.write("            <li><a href=\"index.html#/testcase-list\">Test cases</a></li>\n");
      out.write("            \n");
      out.write("              <li><a href=\"#/device-list\">Editor</a></li>\n");
      out.write("              \n");
      out.write("              \n");
      out.write("                <li class=\"selected\"><a href=\"/user/dashboard/\">All your fiddles</a></li>\n");
      out.write("                <li><a href=\"index.html\">Devices</a></li>\n");
      out.write("                \n");
      out.write("                \n");
      out.write("              \n");
      out.write("            </ul> <!-- /commonNav -->\n");
      out.write("            <span id=\"shadow\"></span>\n");
      out.write("          </header>\n");
      out.write("          <div id=\"body\">\n");
      out.write("            \n");
      out.write("\n");
      out.write("            \n");
      out.write("  \n");
      out.write("\n");
      out.write("    <div class=\"blankslate\">\n");
      out.write("\t  \n");
      out.write("      <h2>You don't have any Fiddles yet.</h2>\n");
      out.write("      <p>You will find all your fiddles here after you will <a title=\"Create a new Fiddle\" href=\"/\">create</a> or fork them.</p>\n");
      out.write("    </div> <!-- /blankslate -->\n");
      out.write("\n");
      out.write("  \n");
      out.write("\n");
      out.write("  \n");
      out.write("\n");
      out.write("\n");
      out.write("          </div> <!-- /body -->\n");
      out.write("        </div> <!-- /content -->\n");
      out.write("      </div> <!-- /contentWrap -->\n");
      out.write("\n");
      out.write("      <div class=\"sidebarWrap\">\n");
      out.write("        <div id=\"sidebar\">\n");
      out.write("          <ul class=\"commonNav\" id=\"side-nav\">\n");
      out.write("            \n");
      out.write("              <li><a href=\"/user/logout/\">Sign out</a></li>\n");
      out.write("              <li><a href=\"/user/dashboard/edit/\">Edit your profile</a></li>\n");
      out.write("            \n");
      out.write("          </ul> <!-- /commonNav -->\n");
      out.write("          \n");
      out.write("  \n");
      out.write("<div class=\"segment\">\n");
      out.write("  <div class=\"face\">\n");
      out.write("    <a href=\"/user/dashboard/\"><img src=\"http://www.gravatar.com/avatar/036785b6c345a739ed57578650624979/?default=&amp;s=160\" height=\"80\" width=\"80\" /></a>\n");
      out.write("    <h3></h3>\n");
      out.write("    <p> ");
      out.print(session.getAttribute("name"));
      out.write("</p>\n");
      out.write("  </div> <!-- /face -->\n");
      out.write("  \n");
      out.write("    <ul class=\"userDetails\">\n");
      out.write("      \n");
      out.write("      \n");
      out.write("      \n");
      out.write("      \n");
      out.write("      \n");
      out.write("    </ul> <!-- /userDetails -->\n");
      out.write("  \n");
      out.write("</div> <!-- /segment -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("          <script async type=\"text/javascript\" src=\"//cdn.carbonads.com/carbon.js?zoneid=1673&serve=C6AILKT&placement=jsfiddlenet\" id=\"_carbonads_js\"></script>\n");
      out.write("          \n");
      out.write("        </div> <!-- /sidebar -->\n");
      out.write("      </div> <!-- /sidebarWrap -->\n");
      out.write("\n");
      out.write("\n");
      out.write("    <script src=\"assets/plugins/jquery-1.10.2.js\"></script>\n");
      out.write("    <!-- BOOTSTRAP CORE SCRIPT   -->\n");
      out.write("    <script src=\"assets/plugins/bootstrap.js\"></script>\n");
      out.write("  \n");
      out.write("    <!-- CUSTOM SCRIPTS -->\n");
      out.write("    <script src=\"assets/js/custom.js\"></script>\n");
      out.write("<!-- JQuery ================================================================ -->\n");
      out.write("<script src=\"js/jquery/jquery-2.0.3.js\"></script>\n");
      out.write("\n");
      out.write("<!-- Bootstrap ============================================================= -->\n");
      out.write("<script src=\"js/bootstrap/bootstrap.js\"></script>\n");
      out.write("\n");
      out.write("<!-- AngularJS ============================================================= -->\n");
      out.write("<!-- In production use:\n");
      out.write("<script src=\"//ajax.googleapis.com/ajax/libs/angularjs/1.0.7/angular.min.js\"></script>\n");
      out.write("-->\n");
      out.write("<script src=\"lib/angular/angular.js\"></script>\n");
      out.write("<script src=\"lib/angular/angular-resource.js\"></script>\n");
      out.write("\n");
      out.write("<!-- AngularJS App Code ==================================================== -->\n");
      out.write("<script src=\"js/app.js\"></script>\n");
      out.write("<script src=\"js/services.js\"></script>\n");
      out.write("<script src=\"js/controllers.js\"></script>\n");
      out.write("<script src=\"js/filters.js\"></script>\n");
      out.write("<script src=\"js/directives.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
