/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2016-01-07 22:13:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import javax.sql.*;
import java.sql.*;
import java.awt.*;
import java.io.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("  \n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<style>\n");
      out.write("body{\n");
      out.write("color:\"white\";\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<style>\n");
      out.write("\n");
      out.write(" \n");
      out.write("  nav {\n");
      out.write("  margin: 20px;\n");
      out.write("}  \n");
      out.write(" \n");
      out.write(" ul {\n");
      out.write("  /* //overflow: auto; */\n");
      out.write("  list-style-type: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("li {\n");
      out.write("  height: 15px;\n");
      out.write("  float: left;\n");
      out.write("  margin-right: 0px;\n");
      out.write("  border-right: 1px solid #aaa;\n");
      out.write("  padding: 0 10px;\n");
      out.write("}\n");
      out.write(" \n");
      out.write("li:last-child {\n");
      out.write("  border-right: none;\n");
      out.write("}\n");
      out.write(" \n");
      out.write("li a {\n");
      out.write("  text-decoration: none;\n");
      out.write("  color: #3399ff;\n");
      out.write("  font: 15px/1 Helvetica, Verdana, sans-serif;\n");
      out.write("  font-color:#3399ff;\n");
      out.write("  text-transform: uppercase;\n");
      out.write(" \n");
      out.write("  -webkit-transition: all 0.5s ease;\n");
      out.write("  -moz-transition: all 0.5s ease;\n");
      out.write("  -o-transition: all 0.5s ease;\n");
      out.write("  -ms-transition: all 0.5s ease;\n");
      out.write("  transition: all 0.5s ease;\n");
      out.write("}\n");
      out.write(" \n");
      out.write("li a:hover {\n");
      out.write("  color: #666;\n");
      out.write("}\n");
      out.write(" \n");
      out.write("li.active a {\n");
      out.write("  font-weight: bold;\n");
      out.write("  color: #333;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write(" <style>\n");
      out.write("    .moreinfo {\n");
      out.write("    \t  display: inline-block;\n");
      out.write("    \t} \n");
      out.write("    \tTD{font-family: Arial;\n");
      out.write("    \t font-size: 11pt;}\n");
      out.write("    </style>\n");
      out.write("  \n");
      out.write("     <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js\"></script>\n");
      out.write("\n");
      out.write("     \n");
      out.write("     <!-- <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script>  -->\n");
      out.write("    <script src=\"http://code.highcharts.com/highcharts.js\"></script>\n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("    $( document ).ready(function() {\n");
      out.write("    \t var processed_json = new Array();\n");
      out.write("    \t var processed_json1 = new Array(); \n");
      out.write("    \t \n");
      out.write("    \t var url = window.location.href.split('/');\n");
      out.write("      \t  var baseUrl = url[0] + '//' + url[2]+\"/\"+url[3]+\"/\";\n");
      out.write("      \t  \n");
      out.write("    $.getJSON(baseUrl+'web/devicetests/devicecount/', function(data) {\n");
      out.write("    \tvar out=data;\n");
      out.write("    document.getElementById(\"devicecount\").innerHTML=\"  \"+out;\n");
      out.write("    });\n");
      out.write("    \n");
      out.write("    $.getJSON(baseUrl+'web/devicetests/testcount/', function(data) {\n");
      out.write("    \tvar out=data;\n");
      out.write("    document.getElementById(\"testcount\").innerHTML=\"  \"+out;\n");
      out.write("    });\n");
      out.write("    \n");
      out.write("    $.getJSON(baseUrl+'web/devicetests/errorcount/', function(data) {\n");
      out.write("    \tvar out=data;\n");
      out.write("    document.getElementById(\"errorcount\").innerHTML=\"  \"+out;\n");
      out.write("    });\n");
      out.write("    $.getJSON(baseUrl+'web/devicetests/stats/', function(data) {\n");
      out.write("    \t\n");
      out.write("    \n");
      out.write("    \t\n");
      out.write("    \t\n");
      out.write("    \tvar tripass=data[1]-data[3];\n");
      out.write("    \tvar textpass=data[0]-data[2];\n");
      out.write("    \t\n");
      out.write("        var name = ['Pass','Fail'];\n");
      out.write("  \n");
      out.write("        var data1 = [tripass,data[3]];\n");
      out.write("        var final1 = [];\n");
      out.write("        \n");
      out.write("        //var name1 = ['Pass','Fail'];\n");
      out.write("        var data2 = [textpass,data[2]];\n");
      out.write("        var final2 = [];\n");
      out.write("        \n");
      out.write("        for(var i=0; i < name.length; i++) {\n");
      out.write("        \tfinal1.push({\n");
      out.write("                name: name[i],\n");
      out.write("                y: data1[i]\t\t\t \n");
      out.write("            }); \t   \n");
      out.write("        }    \n");
      out.write("        for(var i=0; i < name.length; i++) {\n");
      out.write("        \tfinal2.push({\n");
      out.write("                name: name[i],\n");
      out.write("                y: data2[i]\t\t\t \n");
      out.write("            }); \t   \n");
      out.write("        }    \n");
      out.write("        Highcharts.setOptions({\n");
      out.write("\t\t  //  colors: [/* '#50B432', '#ED561B', '#DDDF00', '#24CBE5', */ '#64E572', '#FF9655', '#FFF263','#6AF9C4'] \n");
      out.write("\t\t      colors: [/* '#4D4D4D','#5DA5DA','#FAA43A',  */'#60BD68','#F17CB0', '#B2912F', '#B276B2','#DECF3F', '#F15854']  \n");
      out.write("\t\t   });\n");
      out.write("        \n");
      out.write("        Highcharts.getOptions().colors = Highcharts.map(Highcharts.getOptions().colors, function (color) {\n");
      out.write("            return {\n");
      out.write("                radialGradient: {\n");
      out.write("                    cx: 0.5,\n");
      out.write("                    cy: 0.3,\n");
      out.write("                    r: 0.7\n");
      out.write("                },\n");
      out.write("                stops: [\n");
      out.write("                    [0, color],\n");
      out.write("                    [1, Highcharts.Color(color).brighten(-0.5).get('rgb')] // darken\n");
      out.write("                ]\n");
      out.write("            };\n");
      out.write("        });\n");
      out.write("        \n");
      out.write("    \t\n");
      out.write("        $('#container1').highcharts({\n");
      out.write("            chart: {\n");
      out.write("                plotBackgroundColor: null,\n");
      out.write("                plotBorderWidth: null,\n");
      out.write("                plotShadow: false,\n");
      out.write("                type: 'pie'\n");
      out.write("            },\n");
      out.write("            title: {\n");
      out.write("                text: 'Trillian IM'\n");
      out.write("            },\n");
      out.write("            tooltip: {\n");
      out.write("                pointFormat: '{series.name}: <b>{point.y}</b>'\n");
      out.write("            },\n");
      out.write("            plotOptions: {\n");
      out.write("                pie: {\n");
      out.write("                    allowPointSelect: true,\n");
      out.write("                    cursor: 'pointer',\n");
      out.write("                    point: {\n");
      out.write("                        events: {\n");
      out.write("                            click: function () {\n");
      out.write("                                location.href = this.options.url;\n");
      out.write("                            }\n");
      out.write("                        }\n");
      out.write("                    },\n");
      out.write("                    dataLabels: {\n");
      out.write("                        enabled: true,\n");
      out.write("                       /*  formatter: function() {\n");
      out.write("                             return this.name+\":\"+this.y;\n");
      out.write("                          }, */\n");
      out.write("                          style: {\n");
      out.write("                              color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'\n");
      out.write("                          },\n");
      out.write("                       // distance: -30\n");
      out.write("                      //  color:'white'\n");
      out.write("                    },\n");
      out.write("           /*  startAngle: -90,\n");
      out.write("            endAngle: 90,\n");
      out.write("            center: ['50%', '75%'] */\n");
      out.write("                }\n");
      out.write("            \n");
      out.write("            },\n");
      out.write("            series: [{\n");
      out.write("            \t data: [{\n");
      out.write("            \t\t name:\"Pass\",\n");
      out.write("                     y: tripass,\n");
      out.write("                     url: baseUrl+'table-data.jsp?query=trillianpass'\n");
      out.write("                 }, {\n");
      out.write("                \t name:\"Fail\",\n");
      out.write("                     y: data[3],\n");
      out.write("                     url: baseUrl+'table-data.jsp?query=trillianfail',\n");
      out.write("                     color:'#ff0000'\t\t \n");
      out.write("                 }]\n");
      out.write("            }]\n");
      out.write("        });\n");
      out.write("  \t\n");
      out.write("        $('#container2').highcharts({\n");
      out.write("            chart: {\n");
      out.write("                plotBackgroundColor: null,\n");
      out.write("                plotBorderWidth: null,\n");
      out.write("                plotShadow: false,\n");
      out.write("                type: 'pie'\n");
      out.write("            },\n");
      out.write("            title: {\n");
      out.write("                text: 'Texting'\n");
      out.write("            },\n");
      out.write("            tooltip: {\n");
      out.write("                pointFormat: '{series.name}: <b>{point.y}</b>'\n");
      out.write("            },\n");
      out.write("            plotOptions: {\n");
      out.write("                pie: {\n");
      out.write("                    allowPointSelect: true,\n");
      out.write("                    cursor: 'pointer',\n");
      out.write("                    point: {\n");
      out.write("                        events: {\n");
      out.write("                            click: function () {\n");
      out.write("                                location.href = this.options.url;\n");
      out.write("                            }\n");
      out.write("                        }\n");
      out.write("                    },\n");
      out.write("                    dataLabels: {\n");
      out.write("                        enabled: true,\n");
      out.write("                        style: {\n");
      out.write("                            color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'\n");
      out.write("                        }\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("            \n");
      out.write("            },\n");
      out.write("            series: [{\n");
      out.write("           \t data: [{\n");
      out.write("           \t\t name:\"Pass\",\n");
      out.write("                    y: textpass,\n");
      out.write("                    url: baseUrl+'table-data.jsp?query=textpass'\n");
      out.write("                }, {\n");
      out.write("               \t name:\"Fail\",\n");
      out.write("                    y: data[2],\n");
      out.write("                    url: baseUrl+'table-data.jsp?query=textfail',\n");
      out.write("                    color:'#ff0000'\n");
      out.write("                }]\n");
      out.write("           }]\n");
      out.write("        });\n");
      out.write("  \t \n");
      out.write(" \n");
      out.write("    });\n");
      out.write("    \n");
      out.write("    });\n");
      out.write("    </script>\n");
      out.write("<style type=\"text/css\" media=\"screen\">\n");
      out.write("            #carbonads {\n");
      out.write("              padding: 20px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            #carbonads .carbon-img {\n");
      out.write("              clear: both;\n");
      out.write("              float: left;\n");
      out.write("              background: #fff;\n");
      out.write("              padding: 10px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            #carbonads .carbon-img img {\n");
      out.write("              display: block;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            #carbonads .carbon-text {\n");
      out.write("              clear: both;\n");
      out.write("              display: block;\n");
      out.write("              padding: 10px 0;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            #carbonads .carbon-poweredby {\n");
      out.write("              display: block;\n");
      out.write("              color: #ADB0BA;\n");
      out.write("              font-size: .9em;\n");
      out.write("            }\n");
      out.write("          </style>\n");
      out.write("\n");
      out.write("    <title> MCELLBLOCK</title>\n");
      out.write("    <!--REQUIRED STYLE SHEETS-->\n");
      out.write("    <!-- BOOTSTRAP CORE STYLE CSS -->\n");
      out.write("    <link href=\"assets/css/bootstrap.css\" rel=\"stylesheet\" />\n");
      out.write("    <!-- FONTAWESOME STYLE CSS -->\n");
      out.write("    <link href=\"assets/css/font-awesome.min.css\" rel=\"stylesheet\" />\n");
      out.write("   <!--  ANIMATED FONTAWESOME STYLE CSS -->\n");
      out.write("    <!-- <link href=\"assets/css/font-awesome-animation.css\" rel=\"stylesheet\" />  -->\n");
      out.write("     <link href=\"css/session.css\" rel=\"stylesheet\" /> \n");
      out.write("    <link href=\"css/elusive-webfont.css\" rel=\"stylesheet\" />\n");
      out.write("    <link href=\"css/pages.css\" rel=\"stylesheet\" />\n");
      out.write("    <link href=\"css/sunburst.css\" rel=\"stylesheet\" />\n");
      out.write("       <!-- CUSTOM STYLE CSS -->\n");
      out.write("    <!-- <link href=\"assets/css/style.css\" rel=\"stylesheet\" /> -->\n");
      out.write("    <!-- GOOGLE FONT -->\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    \n");
      out.write("      <div class=\"contentWrap\">\n");
      out.write("        <div id=\"content\">\n");
      out.write("          <header>\n");
      out.write("          <h1 style=\"margin-left:-20px;margin-top:-30px;\"><img  src=\"img/bootstrap/mobile-integration-workgroup-squarelogo.png\" border=\"0\" alt=\"MIW\" style=\"margin-bottom:'0px';height:80px;width:'80px;'\"/></h1>\n");
      out.write("          <nav>\n");
      out.write("            <ul class=\"commonNav\" id=\"main-nav\">\n");
      out.write("            \n");
      out.write("            <li><a href=\"index.html#/testcase-list\">Test cases</a></li>\n");
      out.write("            \n");
      out.write("             <!--  <li><a href=\"#/device-list\">Editor</a></li> -->\n");
      out.write("              \n");
      out.write("              \n");
      out.write("                <li class=\"selected\"><a href=\"/user/dashboard/\"><font color=\"#3399ff\"><bold>Dashboard</bold></font></a></li>\n");
      out.write("                <li><a href=\"index.html\">Devices</a></li>\n");
      out.write("                \n");
      out.write("                \n");
      out.write("              \n");
      out.write("            </ul> <!-- /commonNav -->\n");
      out.write("            </nav>\n");
      out.write("            <span id=\"shadow\"></span>\n");
      out.write("          </header>\n");
      out.write("          <div id=\"body\">\n");
      out.write(" <div class=\"blankslate\">\n");
      out.write("\t  <!-- \n");
      out.write("      <h2>You don't have any Fiddles yet.</h2>\n");
      out.write("      <p>You will find all your fiddles here after you will <a title=\"Create a new Fiddle\" href=\"/\">create</a> or fork them.</p>\n");
      out.write("       -->\n");
      out.write("      <div class=\"moreinfo\" style=\"margin-left:40px;\">\n");
      out.write("      <button style=\"width:85px;height:45px;background-color:#ff6600;border:#ff6600;\" id=\"devicecount\" class=\" btn glyphicon glyphicon-phone btn-danger\"></button>\n");
      out.write("      </br></br><span style=\"margin-left:10px;font-family='Tahoma'\"><font size=\"2.5px;\" >DEVICES</font></span>\n");
      out.write("      </br><span style=\"margin-left:5px;font-family='Tahoma'\"><font size=\"1.5px;\" >WERE TESTED.</font></span>\n");
      out.write("      </div>\n");
      out.write("        <div style=\"margin-left:90px;\" class=\"moreinfo\">\n");
      out.write("      <button style=\"width:85px;height:45px;background-color: #3399ff; border:#3399ff;\" id=\"testcount\" class=\" btn glyphicon glyphicon-credit-card btn-danger\"></button>\n");
      out.write("      </br></br><span style=\"margin-left:10px;font-family='Tahoma'\"><font size=\"2.5px;\" >TESTS</font></span>\n");
      out.write("      </br><span style=\"margin-left:5px;font-family='Tahoma'\"><font size=\"1.5px;\" >WERE RUN.</font></span>\n");
      out.write("      </div>\n");
      out.write("          <div style=\"margin-left:90px;\" class=\"moreinfo\">\n");
      out.write("      <button style=\"width:85px;height:45px;background-color: #ff0000; border:#ff0000;\" id=\"errorcount\" class=\" btn glyphicon glyphicon-ban-circle btn-danger\"></button>\n");
      out.write("      </br></br><span style=\"margin-left:10px;font-family='Tahoma'\"><font size=\"2.5px;\" >TESTS</font></span>\n");
      out.write("      </br><span style=\"margin-left:5px;font-family='Tahoma'\"><font size=\"1.5px;\" >WERE FAILED.</font></span>\n");
      out.write("      </div>\n");
      out.write("      </br></br></br>\n");
      out.write("      <div>\n");
      out.write("     \n");
      out.write("  <div class=\"moreinfo\" id=\"container1\" style=\"height:300px;width:300px;\" >\n");
      out.write("  </div>\n");
      out.write("  <div class=\"moreinfo\" id=\"container2\" style=\"margin-left:10px;height:300px;width:260px;\"></div> \n");
      out.write("      </div>\n");
      out.write("    </div> <!-- /blankslate -->\n");
      out.write("      </div> <!-- /body -->\n");
      out.write("        </div> <!-- /content -->\n");
      out.write("      </div> <!-- /contentWrap -->\n");
      out.write("\n");
      out.write("      <div class=\"sidebarWrap\">\n");
      out.write("        <div id=\"sidebar\">\n");
      out.write("          <ul class=\"commonNav\" id=\"side-nav\">\n");
      out.write("            \n");
      out.write("              <li><a href=\"signout-done.jsp\">Sign out</a></li>\n");
      out.write("              <li><a href=\"#\">Edit your profile</a></li>\n");
      out.write("            \n");
      out.write("          </ul> <!-- /commonNav -->\n");
      out.write("          \n");
      out.write("  \n");
      out.write("<div class=\"segment\">\n");
      out.write("  <div class=\"face\">\n");
      out.write("    <a href=\"#\"><img src=\"http://www.gravatar.com/avatar/036785b6c345a739ed57578650624979/?default=&amp;s=160\" height=\"80\" width=\"80\" /></a>\n");
      out.write("    <h3></h3>\n");
      out.write("    <p> ");
      out.print(session.getAttribute("name"));
      out.write("</p>\n");
      out.write("  </div> <!-- /face -->\n");
      out.write("  \n");
      out.write("    <ul class=\"userDetails\">\n");
      out.write("   </ul>\n");
      out.write("  \n");
      out.write("</div>\n");
      out.write("       \n");
      out.write("        </div>\n");
      out.write("      </div> \n");
      out.write("<!-- \n");
      out.write("    <script src=\"assets/plugins/jquery-1.10.2.js\"></script>\n");
      out.write("    BOOTSTRAP CORE SCRIPT  \n");
      out.write("    <script src=\"assets/plugins/bootstrap.js\"></script>\n");
      out.write("  \n");
      out.write("    CUSTOM SCRIPTS\n");
      out.write("    <script src=\"assets/js/custom.js\"></script>\n");
      out.write("JQuery ================================================================\n");
      out.write("<script src=\"js/jquery/jquery-2.0.3.js\"></script> -->\n");
      out.write("\n");
      out.write("<!-- Bootstrap ============================================================= -->\n");
      out.write("<script src=\"js/bootstrap/bootstrap.js\"></script>\n");
      out.write("\n");
      out.write("<script src=\"lib/angular/angular.js\"></script>\n");
      out.write("<script src=\"lib/angular/angular-resource.js\"></script>\n");
      out.write("\n");
      out.write("<!-- AngularJS App Code ==================================================== -->\n");
      out.write("<script src=\"js/app.js\"></script>\n");
      out.write("<script src=\"js/services.js\"></script>\n");
      out.write("<script src=\"js/controllers.js\"></script>\n");
      out.write("<script src=\"js/filters.js\"></script>\n");
      out.write("<script src=\"js/directives.js\"></script>\n");
      out.write("<script src=\"js/highcharts.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
