/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2015-12-16 23:27:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class devicepage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js\"></script>\n");
      out.write("<script src=\"http://code.highcharts.com/highcharts.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("</script>\n");
      out.write("<link href=\"assets/css/bootstrap.css\" rel=\"stylesheet\" />\n");
      out.write("<link href=\"assets/css/font-awesome.min.css\" rel=\"stylesheet\" />\n");
      out.write("<link href=\"css/session.css\" rel=\"stylesheet\" /> \n");
      out.write("<link href=\"css/elusive-webfont.css\" rel=\"stylesheet\" />\n");
      out.write("<link href=\"css/pages.css\" rel=\"stylesheet\" />\n");
      out.write("<link href=\"css/sunburst.css\" rel=\"stylesheet\" />\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write(".modal.modal-wide .modal-dialog {\n");
      out.write("  width: 90%;\n");
      out.write("}\n");
      out.write(".modal-wide .modal-body {\n");
      out.write("  overflow-y: auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* irrelevant styling */\n");
      out.write("body { text-align: center; }\n");
      out.write("body p { \n");
      out.write("  max-width: 400px; \n");
      out.write("  margin: 20px auto; \n");
      out.write("}\n");
      out.write("#tallModal .modal-body p { margin-bottom: 900px }\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<a data-toggle=\"modal\" href=\"#normalModal\" class=\"btn btn-default\">Normal</a>\n");
      out.write("\n");
      out.write("<a data-toggle=\"modal\" href=\"#tallModal\" class=\"btn btn-primary\">Wide, Tall Content</a>\n");
      out.write("\n");
      out.write("<a data-toggle=\"modal\" href=\"#shortModal\" class=\"btn btn-primary\">Wide, Short Content</a>\n");
      out.write("\n");
      out.write("<div id=\"normalModal\" class=\"modal fade\">\n");
      out.write("  <div class=\"modal-dialog\">\n");
      out.write("    <div class=\"modal-content\">\n");
      out.write("      <div class=\"modal-header\">\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>\n");
      out.write("        <h4 class=\"modal-title\">Modal title</h4>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"modal-body\">\n");
      out.write("        <iframe frameborder=\"0\" scrolling=\"no\" width=\"700\" height=\"700\" src=\"http://google.about.com/b/2013/04/01/google-nose.htm\">\n");
      out.write("        </iframe>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"modal-footer\">\n");
      out.write("        <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\n");
      out.write("        <button type=\"button\" class=\"btn btn-primary\">Save changes</button>\n");
      out.write("      </div>\n");
      out.write("    </div><!-- /.modal-content -->\n");
      out.write("  </div><!-- /.modal-dialog -->\n");
      out.write("</div><!-- /.modal -->\n");
      out.write("\n");
      out.write("<div id=\"tallModal\" class=\"modal modal-wide fade\">\n");
      out.write("  <div class=\"modal-dialog\">\n");
      out.write("    <div class=\"modal-content\">\n");
      out.write("      <div class=\"modal-header\">\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>\n");
      out.write("        <h4 class=\"modal-title\">Modal title</h4>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"modal-body\">\n");
      out.write("        <iframe frameborder=\"0\" scrolling=\"no\" width=\"700\" height=\"500\" src=\"dashboard.jsp\">\n");
      out.write("        </iframe>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"modal-footer\">\n");
      out.write("        <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\n");
      out.write("        <button type=\"button\" class=\"btn btn-primary\">Save changes</button>\n");
      out.write("      </div>\n");
      out.write("    </div><!-- /.modal-content -->\n");
      out.write("  </div><!-- /.modal-dialog -->\n");
      out.write("</div><!-- /.modal -->\n");
      out.write("\n");
      out.write("<div id=\"shortModal\" class=\"modal modal-wide fade\">\n");
      out.write("  <div class=\"modal-dialog\">\n");
      out.write("    <div class=\"modal-content\">\n");
      out.write("      <div class=\"modal-header\">\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>\n");
      out.write("        <h4 class=\"modal-title\">Modal title</h4>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"modal-body\">\n");
      out.write("        <p>One fine body&hellip;</p>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"modal-footer\">\n");
      out.write("        <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\n");
      out.write("        <button type=\"button\" class=\"btn btn-primary\">Save changes</button>\n");
      out.write("      </div>\n");
      out.write("    </div><!-- /.modal-content -->\n");
      out.write("  </div><!-- /.modal-dialog -->\n");
      out.write("</div><!-- /.modal -->\n");
      out.write("</body>\n");
      out.write("<script src=\"js/bootstrap/bootstrap.js\"></script>\n");
      out.write("\n");
      out.write("<script src=\"lib/angular/angular.js\"></script>\n");
      out.write("<script src=\"lib/angular/angular-resource.js\"></script>\n");
      out.write("\n");
      out.write("<!-- AngularJS App Code ==================================================== -->\n");
      out.write("<script src=\"js/app.js\"></script>\n");
      out.write("<script src=\"js/services.js\"></script>\n");
      out.write("<script src=\"js/controllers.js\"></script>\n");
      out.write("<script src=\"js/filters.js\"></script>\n");
      out.write("<script src=\"js/directives.js\"></script>\n");
      out.write("<script src=\"js/highcharts.js\"></script>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
