/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2016-01-23 01:02:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dummynew_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<style>\n");
      out.write("body{\n");
      out.write("color:\"white\";\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("    <title> MCELLBLOCK</title>\n");
      out.write("    <link href=\"assets/css/bootstrap.css\" rel=\"stylesheet\" />\n");
      out.write("    <link href=\"assets/css/font-awesome.min.css\" rel=\"stylesheet\" />\n");
      out.write("     <link href=\"css/session.css\" rel=\"stylesheet\" /> \n");
      out.write("    <link href=\"css/elusive-webfont.css\" rel=\"stylesheet\" />\n");
      out.write("    <link href=\"css/pages.css\" rel=\"stylesheet\" />\n");
      out.write("    <link href=\"css/sunburst.css\" rel=\"stylesheet\" />\n");
      out.write("     \n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>\n");
      out.write("</head>\n");
      out.write("<div id=\"session\">\n");
      out.write("    <h1> <img src=\"img/bootstrap/mobile-integration-workgroup-squarelogo.png\" border=\"0\" alt=\"MIW\" style=\"margin-bottom:'0px';height:80px;width:'80px;'\"/></h1>\n");
      out.write("    <h2>Log in</h2>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <form class=\"commonForm\" id=\"session-form\" method=\"post\" action=\"signinServlet\" accept-charset=\"utf-8\">\n");
      out.write("      <fieldset>\n");
      out.write("        <div style='display:none'></div>\n");
      out.write("        <p><label for=\"id_username\">Username:</label> <input id=\"id_username\" type=\"text\" placeholder=\"username\" name=\"username\" maxlength=\"30\" /></p>\n");
      out.write("<p><label for=\"id_password\">Password:</label> <input type=\"password\" placeholder=\"password\" name=\"password\" id=\"id_password\" /></p>\n");
      out.write("        <div class=\"submitCont\">\n");
      out.write("          <input type=\"submit\" value=\"Log in\" />\n");
      out.write("        </div>\n");
      out.write("      </fieldset>\n");
      out.write("     <!--  <p>\n");
      out.write("        <a href=\"/ngdemo1/signup.jsp\">Sign up</a> or <a href=\"/ngdemo/reset_password.html\">reset your password</a>\n");
      out.write("      </p> -->\n");
      out.write("    </form> <!-- /commonForm -->\n");
      out.write("  </div> <!-- /session -->\n");
      out.write("\n");
      out.write("    <script src=\"assets/plugins/jquery-1.10.2.js\"></script>\n");
      out.write("    <!-- BOOTSTRAP CORE SCRIPT   -->\n");
      out.write("    <script src=\"assets/plugins/bootstrap.js\"></script>\n");
      out.write("  \n");
      out.write("    <!-- CUSTOM SCRIPTS -->\n");
      out.write("    <script src=\"assets/js/custom.js\"></script>\n");
      out.write("<!-- JQuery ================================================================ -->\n");
      out.write("<script src=\"js/jquery/jquery-2.0.3.js\"></script>\n");
      out.write("\n");
      out.write("<!-- Bootstrap ============================================================= -->\n");
      out.write("<script src=\"js/bootstrap/bootstrap.js\"></script>\n");
      out.write("\n");
      out.write("<!-- AngularJS ============================================================= -->\n");
      out.write("<!-- In production use:\n");
      out.write("<script src=\"//ajax.googleapis.com/ajax/libs/angularjs/1.0.7/angular.min.js\"></script>\n");
      out.write("-->\n");
      out.write("<script src=\"lib/angular/angular.js\"></script>\n");
      out.write("<script src=\"lib/angular/angular-resource.js\"></script>\n");
      out.write("\n");
      out.write("<!-- AngularJS App Code ==================================================== -->\n");
      out.write("<script src=\"js/app.js\"></script>\n");
      out.write("<script src=\"js/services.js\"></script>\n");
      out.write("<script src=\"js/controllers.js\"></script>\n");
      out.write("<script src=\"js/filters.js\"></script>\n");
      out.write("<script src=\"js/directives.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
