/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2015-12-15 22:41:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class homegraphs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<style>\n");
      out.write("* {\n");
      out.write("padding: 0;\n");
      out.write("margin: 0;\n");
      out.write("}\n");
      out.write("body {\n");
      out.write("font-size: 73%;\n");
      out.write("font-family: verdana, arial, helvetica, sans-serif;\n");
      out.write("padding: 10px;\n");
      out.write("}\n");
      out.write("#navigation {\n");
      out.write("overflow: auto;\n");
      out.write("}\n");
      out.write("#navigation li {\n");
      out.write("float: left;\n");
      out.write("list-style: none;\n");
      out.write("background-color: #666; /* to cater for users without images */\n");
      out.write("}\n");
      out.write("#navigation a {\n");
      out.write("display: block;\n");
      out.write("background-image: url(css-tabs/tabright.gif);\n");
      out.write("background-position: top right;\n");
      out.write("background-repeat: no-repeat;\n");
      out.write("color: #FFF;\n");
      out.write("text-decoration: none;\n");
      out.write("font-weight: bold;*/\n");
      out.write("}\n");
      out.write("#navigation span {\n");
      out.write("display: block;\n");
      out.write("background-image: url(css-tabs/tableft.gif);\n");
      out.write("background-repeat: no-repeat;\n");
      out.write("padding: 5px 15px;\n");
      out.write("}\n");
      out.write("#navigation a:hover {\n");
      out.write("background-position: right -198px;\n");
      out.write("}\n");
      out.write("#navigation a:hover span {\n");
      out.write("background-position: 0 -198px;\n");
      out.write("}\n");
      out.write("#navigation li ul {\n");
      out.write("position: absolute;\n");
      out.write("width: 10em;\n");
      out.write("left: -999em;\n");
      out.write("margin-left: 2px;\n");
      out.write("font-size: 90%;\n");
      out.write("}\n");
      out.write("#navigation li ul a, #navigation li ul a:link {\n");
      out.write("background-image: none;\n");
      out.write("padding: 5px;\n");
      out.write("width: 10em;\n");
      out.write("background-color: #666;\n");
      out.write("}\n");
      out.write("#navigation li ul a:hover {\n");
      out.write("background-color: #333;\n");
      out.write("}\n");
      out.write("#navigation li:hover ul, #navigation li.sfhover ul {\n");
      out.write("left: auto;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<ul id=\"navigation\">\n");
      out.write("<li><a href=\"#\"><span>Home</span></a></li>\n");
      out.write("<li><a href=\"#\"><span>About</span></a>\n");
      out.write("<ul>\n");
      out.write("<li><a href=\"#\">My Qualifications</a></li>\n");
      out.write("<li><a href=\"#\">My Personal Details</a></li>\n");
      out.write("</ul>\n");
      out.write("</li>\n");
      out.write("<li><a href=\"#\"><span>Services</span></a>\n");
      out.write("<ul>\n");
      out.write("<li><a href=\"#\">HTML</a></li>\n");
      out.write("<li><a href=\"#\">CSS</a></li>\n");
      out.write("<li><a href=\"#\">Accessibility</a></li>\n");
      out.write("</ul>\n");
      out.write("</li>\n");
      out.write("<li><a href=\"#\"><span>Portfolio</span></a></li>\n");
      out.write("<li><a href=\"#\"><span>Contact</span></a></li>\n");
      out.write("<li><a href=\"#\"><span>Links</span></a></li>\n");
      out.write("</ul>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
