/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2015-12-17 18:44:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import javax.sql.*;
import java.sql.*;
import java.awt.*;
import java.io.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write(" <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css\">\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script>\n");
      out.write("  <script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("$(document).ready(function(){\n");
      out.write("\t        $(\"#myModal\").modal();\n");
      out.write("\t});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("  <title>MCellBlock</title>\n");
      out.write("  <style>\n");
      out.write("   .logo {\n");
      out.write("      float:left;\n");
      out.write("      width:20%;\n");
      out.write("      height:12%;\n");
      out.write("    }\n");
      out.write("    .devices {\n");
      out.write("      float:left;\n");
      out.write("      width:20%;\n");
      out.write("      height:81%;\n");
      out.write("    }\n");
      out.write("    .menu {\n");
      out.write("      width:78%;\n");
      out.write("      height:12%;\n");
      out.write("    }\n");
      out.write("    .mainContent {\n");
      out.write("      float:left;\n");
      out.write("      width:40%;\n");
      out.write("      height:80%;\n");
      out.write("    }\n");
      out.write("    .mainContent1 {\n");
      out.write("      width:22%;\n");
      out.write("      height:80%;\n");
      out.write("    }\n");
      out.write("     .mainContent2 {\n");
      out.write("      width:15%;\n");
      out.write("      height:80%;\n");
      out.write("    }\n");
      out.write("    .footer {\n");
      out.write("    float:left;\n");
      out.write("      width:98.2%;\n");
      out.write("      height:8%;\n");
      out.write("    }\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<iframe class=\"logo block\" frameborder=\"0\" scrolling=\"no\"\n");
      out.write("   src=\"img/bootstrap/logo_165565_20150921051734.png\" name=\"imgbox\" id=\"imgbox\">\n");
      out.write("</iframe>\n");
      out.write("  <iframe class=\"menu block\"  frameborder=\"0\" scrolling=\"no\" src=\"menu.jsp\">\n");
      out.write(" \n");
      out.write("  </iframe>\n");
      out.write("   <iframe class=\"devices\"   frameborder=\"0\"  src=\"partials/devices.html\">\n");
      out.write("   </iframe>\n");
      out.write("  <iframe class=\"mainContent\"  name=\"mainContent\" frameborder=\"0\" scrolling=\"no\" src=\"homegraphs.jsp\">\n");
      out.write("  </iframe>\n");
      out.write("   <iframe class=\"mainContent1\" frameborder=\"0\" scrolling=\"no\" src=\"container1.jsp\"></iframe>\n");
      out.write("    <iframe class=\"mainContent2\" frameborder=\"0\" scrolling=\"no\"  src=\"container2.jsp\"></iframe>\n");
      out.write("     <iframe class=\"footer\"  frameborder=\"0\" scrolling=\"no\" src=\"footer.jsp\" ></iframe>\n");
      out.write("     <!-- style=\"border: 3px solid #EEE;\" -->\n");
      out.write("  \n");
      out.write("    <div class=\"container\">\n");
      out.write("  <div class=\"modal fade\" id=\"myModal\" role=\"dialog\">\n");
      out.write("    <div class=\"modal-dialog\">\n");
      out.write("    \n");
      out.write("      <!-- Modal content-->\n");
      out.write("      <div class=\"modal-content\">\n");
      out.write("        <div class=\"modal-header\">\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n");
      out.write("          <h4 class=\"modal-title\">Modal Header</h4>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"modal-body\">\n");
      out.write("          <p>Some text in the modal.</p>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"modal-footer\">\n");
      out.write("          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      \n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("\n");
      out.write("<script src=\"js/bootstrap/bootstrap.js\"></script>\n");
      out.write("\n");
      out.write("<script src=\"lib/angular/angular.js\"></script>\n");
      out.write("<script src=\"lib/angular/angular-resource.js\"></script>\n");
      out.write("\n");
      out.write("<!-- AngularJS App Code ==================================================== -->\n");
      out.write("<script src=\"js/app.js\"></script>\n");
      out.write("<script src=\"js/services.js\"></script>\n");
      out.write("<script src=\"js/controllers.js\"></script>\n");
      out.write("<script src=\"js/filters.js\"></script>\n");
      out.write("<script src=\"js/directives.js\"></script>\n");
      out.write("<script src=\"js/highcharts.js\"></script>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
