/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2015-12-15 18:35:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import javax.sql.*;
import java.sql.*;
import java.awt.*;
import java.io.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js\"></script>\n");
      out.write("<script src=\"http://code.highcharts.com/highcharts.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("$(document).ready(function() { \n");
      out.write("\t//alert(\"inside\");\n");
      out.write("    $('#pageContent').load('loadcharts.jsp');\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("body{\n");
      out.write("font-family: \"Open Sans\",sans-serif;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<style>\n");
      out.write("#logo { width:200px; height: 50px; background:white; float:left; border: 1px solid #e6e6e6;border-radius:1px;}\n");
      out.write("#menu { width:1065px; height: 50px; float:left;border: 1px solid #e6e6e6;border-radius:1px;background-color: #4d4d4d; }\n");
      out.write("#graphs { width:500px; height: 630px; background:white;border: 1px solid #4d4d4d;border-radius:1px;}\n");
      out.write("#devices { width:200px;height: 580px; background:white;float:left;border: 1px solid #e6e6e6;border-radius:1px;}\n");
      out.write("#right1 {min-height:580px;background:white;width:620px;float:left;border: 1px solid #e6e6e6;border-radius:1px;}\n");
      out.write("#right2 {min-height:580px;background:white;width:280px;float:left;border: 1px solid #e6e6e6;border-radius:1px;}\n");
      out.write("#right3 {min-height:580px;background:white;width:160px;float:left;border: 1px solid #e6e6e6;border-radius:1px;}\n");
      out.write("#box {background-color: lightgrey; width: 300px;padding: 5px;border: 5px solid #e6e6e6;margin: 5px;}\n");
      out.write("#rcorners1 {   border-radius: 25px;background: #73AD21; padding: 20px; width: 200px;height: 150px;}\n");
      out.write(".break { clear:both }\n");
      out.write("#below { height:25px; width:1265px; background:white;border: 1px solid #e6e6e6; }\n");
      out.write("span{\n");
      out.write("font-family: ubuntu;\n");
      out.write("font-size:13.5px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<style>\n");
      out.write("\n");
      out.write(".divborder{\n");
      out.write("border: 0.5px solid #e6e6e6;height:25px;background-color: #4d4d4d;color: #e6e6e6;\n");
      out.write("}\n");
      out.write(" ul {\n");
      out.write("  /* //overflow: auto; */\n");
      out.write("  list-style-type: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("li {\n");
      out.write("  height: 15px;\n");
      out.write("  float: left;\n");
      out.write("  margin-right: 0px;\n");
      out.write("  border-right: 1px solid #aaa;\n");
      out.write("  padding: 0 5px;\n");
      out.write("}\n");
      out.write(" \n");
      out.write("li:last-child {\n");
      out.write("  border-right: none;\n");
      out.write("}\n");
      out.write(" \n");
      out.write("li a {\n");
      out.write("  text-decoration: none;\n");
      out.write("  color: #3399ff;\n");
      out.write("  font: 13px/1 Helvetica, Verdana, sans-serif;\n");
      out.write("  font-color:#3399ff;\n");
      out.write("  text-transform: uppercase;\n");
      out.write(" \n");
      out.write("  -webkit-transition: all 0.5s ease;\n");
      out.write("  -moz-transition: all 0.5s ease;\n");
      out.write("  -o-transition: all 0.5s ease;\n");
      out.write("  -ms-transition: all 0.5s ease;\n");
      out.write("  transition: all 0.5s ease;\n");
      out.write("}\n");
      out.write(" \n");
      out.write("li a:hover {\n");
      out.write("  color: #666;\n");
      out.write("}\n");
      out.write(" \n");
      out.write("li.active a {\n");
      out.write("  font-weight: bold;\n");
      out.write("  color: #333;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write(" <link href=\"assets/css/bootstrap.css\" rel=\"stylesheet\" />\n");
      out.write(" <link href=\"assets/css/font-awesome.min.css\" rel=\"stylesheet\" />\n");
      out.write(" <link href=\"css/session.css\" rel=\"stylesheet\" /> \n");
      out.write(" <link href=\"css/elusive-webfont.css\" rel=\"stylesheet\" />\n");
      out.write(" <link href=\"css/pages.css\" rel=\"stylesheet\" />\n");
      out.write(" <link href=\"css/sunburst.css\" rel=\"stylesheet\" />\n");
      out.write(" <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div id=\"logo\">\n");
      out.write("<img src=\"img/bootstrap/logo_165565_20150921051734.png\" alt=\"MIW\" style=\"width:200px;height:50px;\">\n");
      out.write("</div>\n");
      out.write("<div id=\"menu\">\n");
      out.write("</br>\n");
      out.write("<span style=\"margin-left:15px; color: #e6e6e6;\">View</span>\n");
      out.write("<span style=\"margin-left:608px; color: #e6e6e6;\">Search</span>\n");
      out.write("<span style=\"margin-left:25px; color: #e6e6e6;\">Configuration</span>\n");
      out.write("<span style=\"margin-left:25px; color: #e6e6e6;\">User</span>\n");
      out.write("<span style=\"margin-left:25px; color: #e6e6e6;\">Notification</span>\n");
      out.write("</div>\n");
      out.write("<div>\n");
      out.write("<span id=\"devices\">\n");
      out.write("<div style=\"margin-bottom:4px;border: 1px solid #e6e6e6;height:25px;background-color: #4d4d4d;color: #e6e6e6;\"><b>&nbsp;Devices</b></div>\n");
      out.write("<div style=\"margin-bottom:392px;\"></div>\n");
      out.write("<div class=\"divborder\">&nbsp;Groups</div>\n");
      out.write("<div class=\"divborder\">&nbsp;Testing/Tests</div>\n");
      out.write("<div class=\"divborder\">&nbsp;Reporting</div>\n");
      out.write("<div class=\"divborder\">&nbsp;Admin</div>\n");
      out.write("<div class=\"divborder\">&nbsp;Statistics</div>\n");
      out.write("<div class=\"divborder\">&nbsp;Help</div>\n");
      out.write("</span>\n");
      out.write("<span id=\"right1\">\n");
      out.write("<!-- <div id=\"pageContent\"> -->\n");
      out.write("\n");
      out.write("      <div class=\"contentWrap\" style=\"margin-left:260px;\">\n");
      out.write("        <div id=\"content\">\n");
      out.write("          <!-- <header> -->\n");
      out.write("          <nav>\n");
      out.write("            <ul class=\"commonNav\" id=\"main-nav\">\n");
      out.write("            <li><a href=\"index.html#/testcase-list\">Test cases</a></li>\n");
      out.write("            <li class=\"selected\"><a href=\"/user/dashboard/\"><font color=\"#3399ff\"><bold>Dashboard</bold></font></a></li>\n");
      out.write("            <li><a href=\"index.html\">Devices</a></li>\n");
      out.write("            <li><a href=\"index.html\">Tests</a></li>\n");
      out.write("            </ul> \n");
      out.write("            </nav>\n");
      out.write("            <span id=\"shadow\"></span>\n");
      out.write("         <!--  </header> -->\n");
      out.write("        </div> \n");
      out.write("      </div> \n");
      out.write("<!-- \n");
      out.write("</div> -->\n");
      out.write("\n");
      out.write("</span>\n");
      out.write("<span id=\"right2\">\n");
      out.write("<div style=\"border: 1px solid #e6e6e6;height:110px;\">Reporting</div>\n");
      out.write("<div style=\"border: 1px solid #e6e6e6;height:110px;\">Admin</div>\n");
      out.write("<div style=\"border: 1px solid #e6e6e6;height:110px;\">Statistics</div>\n");
      out.write("<div style=\"border: 1px solid #e6e6e6;height:110px;\">Statistics</div>\n");
      out.write("<div style=\"border: 1px solid #e6e6e6;height:130px;\">Statistics</div>\n");
      out.write("</span>\n");
      out.write("<span id=\"right3\"></span>\n");
      out.write("</div>\n");
      out.write("<div class=\"break\"></div>\n");
      out.write("<div id=\"below\">\n");
      out.write("<span  style=\"font-size:10px; margin-bottom:2px;\"><center>MCellBlock is produced by Mobile Integration Workgroup</center></span>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("<script src=\"lib/angular/angular.js\"></script>\n");
      out.write("<script src=\"lib/angular/angular-resource.js\"></script>\n");
      out.write("\n");
      out.write("<!-- AngularJS App Code ==================================================== -->\n");
      out.write("<script src=\"js/app.js\"></script>\n");
      out.write("<script src=\"js/services.js\"></script>\n");
      out.write("<script src=\"js/controllers.js\"></script>\n");
      out.write("<script src=\"js/filters.js\"></script>\n");
      out.write("<script src=\"js/directives.js\"></script>\n");
      out.write("<script src=\"js/highcharts.js\"></script>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
