/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2016-01-07 22:13:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class table_002ddata_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("@import url('http://fonts.googleapis.com/css?family=Amarante');\n");
      out.write("\n");
      out.write("html, body, div, span, applet, object, iframe, h1, h2, h3, h4, h5, h6, p, blockquote, pre, a, abbr, acronym, address, big, cite, code, del, dfn, em, img, ins, kbd, q, s, samp, small, strike, strong, sub, sup, tt, var, b, u, i, center, dl, dt, dd, ol, ul, li, fieldset, form, label, legend, table, caption, tbody, tfoot, thead, tr, th, td, article, aside, canvas, details, embed, figure, figcaption, footer, header, hgroup, menu, nav, output, ruby, section, summary, time, mark, audio, video {\n");
      out.write("  margin: 0;\n");
      out.write("  padding: 0;\n");
      out.write("  border: 0;\n");
      out.write("  font-size: 100%;\n");
      out.write("  font: inherit;\n");
      out.write("  vertical-align: baseline;\n");
      out.write("  outline: none;\n");
      out.write("  -webkit-font-smoothing: antialiased;\n");
      out.write("  -webkit-text-size-adjust: 100%;\n");
      out.write("  -ms-text-size-adjust: 100%;\n");
      out.write("  -webkit-box-sizing: border-box;\n");
      out.write("  -moz-box-sizing: border-box;\n");
      out.write("  box-sizing: border-box;\n");
      out.write("}\n");
      out.write("html { overflow-y: scroll; }\n");
      out.write("body { \n");
      out.write("  background: #eee url('http://i.imgur.com/eeQeRmk.png'); /* http://subtlepatterns.com/weave/ */\n");
      out.write("  font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;\n");
      out.write("  font-size: 80.5%;\n");
      out.write("  font-weight:bold;\n");
      out.write("  line-height: 1;\n");
      out.write("  color: #585858;\n");
      out.write("  padding: 22px 10px;\n");
      out.write("  padding-bottom: 55px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("::selection { background: #5f74a0; color: #fff; }\n");
      out.write("::-moz-selection { background: #5f74a0; color: #fff; }\n");
      out.write("::-webkit-selection { background: #5f74a0; color: #fff; }\n");
      out.write("\n");
      out.write("br { display: block; line-height: 1.6em; } \n");
      out.write("\n");
      out.write("article, aside, details, figcaption, figure, footer, header, hgroup, menu, nav, section { display: block; }\n");
      out.write("ol, ul { list-style: none; }\n");
      out.write("\n");
      out.write("input, textarea { \n");
      out.write("  -webkit-font-smoothing: antialiased;\n");
      out.write("  -webkit-text-size-adjust: 100%;\n");
      out.write("  -ms-text-size-adjust: 100%;\n");
      out.write("  -webkit-box-sizing: border-box;\n");
      out.write("  -moz-box-sizing: border-box;\n");
      out.write("  box-sizing: border-box;\n");
      out.write("  outline: none; \n");
      out.write("}\n");
      out.write("\n");
      out.write("blockquote, q { quotes: none; }\n");
      out.write("blockquote:before, blockquote:after, q:before, q:after { content: ''; content: none; }\n");
      out.write("strong, b { font-weight: bold; } \n");
      out.write("\n");
      out.write("table { border-collapse: collapse; border-spacing: 0; border:2;}\n");
      out.write("img { border: 0; max-width: 100%; }\n");
      out.write("\n");
      out.write("h1 { \n");
      out.write("  font-family: 'Amarante', Tahoma, sans-serif;\n");
      out.write("  font-weight: bold;\n");
      out.write("  font-size: 2.6em;\n");
      out.write("  line-height: 1.7em;\n");
      out.write("  margin-bottom: 10px;\n");
      out.write("  text-align: center;\n");
      out.write("  color:#3399ff;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("/** page structure **/\n");
      out.write("#wrapper {\n");
      out.write("  display: block;\n");
      out.write("  width: 1250px;\n");
      out.write("  background: #fff;\n");
      out.write("  margin: 0 auto;\n");
      out.write("  padding: 10px 17px;\n");
      out.write("  -webkit-box-shadow: 2px 2px 3px -1px rgba(0,0,0,0.35);\n");
      out.write("}\n");
      out.write("\n");
      out.write("#keywords {\n");
      out.write("  margin: 0 auto;\n");
      out.write("  font-size: 1.2em;\n");
      out.write("  margin-bottom: 15px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("#keywords thead {\n");
      out.write("  cursor: pointer;\n");
      out.write("  background: #c9dff0;\n");
      out.write("}\n");
      out.write("#keywords thead tr th { \n");
      out.write("  font-weight: bold;\n");
      out.write("  padding: 12px 30px;\n");
      out.write("  padding-left: 42px;\n");
      out.write("}\n");
      out.write("#keywords thead tr th span { \n");
      out.write("  padding-right: 20px;\n");
      out.write("  background-repeat: no-repeat;\n");
      out.write("  background-position: 100% 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#keywords thead tr th.headerSortUp, #keywords thead tr th.headerSortDown {\n");
      out.write("  background: #acc8dd;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#keywords thead tr th.headerSortUp span {\n");
      out.write("  background-image: url('http://i.imgur.com/SP99ZPJ.png');\n");
      out.write("}\n");
      out.write("#keywords thead tr th.headerSortDown span {\n");
      out.write("  background-image: url('http://i.imgur.com/RkA9MBo.png');\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("#keywords tbody tr { \n");
      out.write("  color: #555;\n");
      out.write("}\n");
      out.write("#keywords tbody tr td {\n");
      out.write("  text-align: center;\n");
      out.write("  padding: 15px 10px;\n");
      out.write("}\n");
      out.write("#keywords tbody tr td.lalign {\n");
      out.write("  text-align: left;\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script> \n");
      out.write("<script src=\"http://code.highcharts.com/highcharts.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("var deviceId;\n");
      out.write("var processed_json = new Array(); \n");
      out.write("var processed_json1 = new Array();  \n");
      out.write("$( document ).ready(function() {\n");
      out.write("    console.log( \"document loaded\" );\t\n");
      out.write("    \tvar pathname = window.location.pathname; // Returns path only\n");
      out.write("    \tvar url      = window.location.href; \n");
      out.write("  deviceId = url.substr(url.indexOf(\"=\") + 1);\n");
      out.write("  //alert(deviceId);\n");
      out.write("  document.getElementById(\"test\").innerHTML=deviceId;\n");
      out.write("  var url = window.location.href.split('/');\n");
      out.write("  var baseUrl = url[0] + '//' + url[2]+\"/\"+url[3]+\"/\";\n");
      out.write("  $.getJSON(baseUrl+'web/devicetests/querydata/'+deviceId, function(data) {\n");
      out.write("\t  \n");
      out.write("\t  if(deviceId=='trillianpass'){\n");
      out.write("\t\t  var head=\"<h1>Trillian Instant Messaging Pass Testcases Report</h1>\";\n");
      out.write("\t  }\n");
      out.write("\t  if(deviceId=='trillianfail'){\n");
      out.write("\t\t  var head=\"<h1>Trillian Instant Messaging Fail Testcases Report</h1>\";\n");
      out.write("\t  }\n");
      out.write("\t  if(deviceId=='textpass'){\n");
      out.write("\t\t  var head=\"<h1>Text Messaging Pass Testcases Report</h1>\";\n");
      out.write("\t  }\n");
      out.write("\t  if(deviceId=='textfail'){\n");
      out.write("\t\t  var head=\"<h1>Text Messaging Fail Testcases Report</h1>\";\n");
      out.write("\t  }\n");
      out.write("\t  \n");
      out.write("\t  var out = \"<div id='wrapper'>\"+head+\"<table id='keywords' cellspacing='0' cellpadding='0'> \"+\n");
      out.write("\t  \"<thead><tr><th>UserId</th><th>DeviceId</th><th>Date and Time taken</th><th>Error</th></tr></thead>\";\n");
      out.write("\t  for(var i=0;i<data.length;i++){\n");
      out.write("\t\t  out=out+\"<tr><td>\"+data[i].userid+\"</td>\"+\"<td>\"+data[i].device+\"</td><td>\"+data[i].date+\", \"+data[i].time+\" ms\"+\"</td>\"+\"<td width='20%'>\"+data[i].errormsg+\"</td></tr>\"\n");
      out.write("\t  }\n");
      out.write("\t  out=out+\"</table></div>\";\n");
      out.write("\t  document.getElementById(\"test\").innerHTML=out;\n");
      out.write("  });\n");
      out.write("  \n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Status Report</title>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("<div id=\"test\">\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
