/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2016-01-27 21:44:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class testcasemap_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\n");
      out.write("<html ng-app=\"plunker\">\n");
      out.write("  <head>\n");
      out.write("  <script data-require=\"angular.js@1.2.8\" data-semver=\"1.2.8\" src=\"https://code.angularjs.org/1.2.8/angular.js\"></script>\n");
      out.write("    <link data-require=\"bootstrap@*\" data-semver=\"3.2.0\" rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.css\" />\n");
      out.write("    <link data-require=\"bootstrap-css@~3.1.1\" data-semver=\"3.1.1\" rel=\"stylesheet\" href=\"//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css\" />\n");
      out.write("    <link data-require=\"font-awesome@*\" data-semver=\"4.2.0\" rel=\"stylesheet\" href=\"//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.2.0/css/font-awesome.css\" />\n");
      out.write("    <script data-require=\"ui-bootstrap@*\" data-semver=\"0.11.0\" src=\"http://angular-ui.github.io/bootstrap/ui-bootstrap-tpls-0.11.0.min.js\"></script>\n");
      out.write("   <!--  <link rel=\"stylesheet\" href=\"style.css\" />\n");
      out.write("    <script src=\"example.js\"></script>\n");
      out.write("    <script src=\"angular.js\"></script>\n");
      out.write("    <script src=\"ui-bootstrap-tpls-0.10.0.js\"></script>\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/styles.css\"> \n");
      out.write("    <script src=\"example.js\"></script>\n");
      out.write("    <script src=\"js/controllers.js\"></script> -->\n");
      out.write("    <script src=\"example.js\"></script>\n");
      out.write("     <script src=\"moment.js\"></script>\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/styles.css\"> \n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("    \n");
      out.write("$(document).ready(function() { \n");
      out.write("\t   $(\"#right\").load(\"dropdown.html\") \n");
      out.write("\t  });\n");
      out.write("</script>\n");
      out.write("    <!-- <link href=\"bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"font-awesome.min.css\" rel=\"stylesheet\"/> -->\n");
      out.write("  \n");
      out.write("  <style>\n");
      out.write(".circle{\n");
      out.write("\tborder-radius: 50%;\n");
      out.write("\tmargin: 0.15em;\n");
      out.write("\tfont-size: 3em;\n");
      out.write("\t}\n");
      out.write(".fa-android{\n");
      out.write("\tbackground: #4099FF;\n");
      out.write("\tcolor: #FFFFFF;\n");
      out.write("  padding: 0.05em 0.07em;\n");
      out.write("\t}\n");
      out.write(".fa-pie-chart{\n");
      out.write("\tbackground: #4099FF;\n");
      out.write("\tcolor: #FFFFFF;\n");
      out.write("  padding: 0.05em 0.07em;\n");
      out.write("\t}\n");
      out.write(".fa-file-o{\n");
      out.write("\tbackground: #4099FF;\n");
      out.write("\tcolor: #FFFFFF;\n");
      out.write("  padding: 0.05em 0.07em;\n");
      out.write("\t}\n");
      out.write("\t.fa-search{\n");
      out.write("\tbackground: #4099FF;\n");
      out.write("\tcolor: #FFFFFF;\n");
      out.write("  padding: 0.05em 0.07em;\n");
      out.write("\t}\n");
      out.write("  #wrapper {\n");
      out.write("  font: 20px Calibri;\n");
      out.write("  width: 100px;\n");
      out.write("  margin: 0 auto;\n");
      out.write("}\n");
      out.write("  body{\n");
      out.write("  background-color:white;\n");
      out.write("  }\n");
      out.write("  .dropdown-submenu{position:relative;}\n");
      out.write(".dropdown-submenu>.dropdown-menu{top:0;left:100%;margin-top:-6px;margin-left:-1px;-webkit-border-radius:0 6px 6px 6px;-moz-border-radius:0 6px 6px 6px;border-radius:0 6px 6px 6px;}\n");
      out.write(".dropdown-submenu:hover>.dropdown-menu{display:block;}\n");
      out.write(".dropdown-submenu>a:after{display:block;content:\" \";float:right;width:0;height:0;border-color:transparent;border-style:solid;border-width:5px 0 5px 5px;border-left-color:#cccccc;margin-top:5px;margin-right:-10px;}\n");
      out.write(".dropdown-submenu:hover>a:after{border-left-color:#ffffff;}\n");
      out.write("div:hover {\n");
      out.write("    background-image:url('arrow.gif');\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("/* div#special {\n");
      out.write("    accordion: inherit;\n");
      out.write("} */\n");
      out.write(".dropdown-submenu.pull-left{float:none;}.dropdown-submenu.pull-left>.dropdown-menu{left:-100%;margin-left:10px;-webkit-border-radius:6px 0 6px 6px;-moz-border-radius:6px 0 6px 6px;border-radius:6px 0 6px 6px;}\n");
      out.write("  </style>  \n");
      out.write("  <style>\n");
      out.write("  body{\n");
      out.write("font-family:Arial, Helvetica, sans-serif; \n");
      out.write("font-size:17px;\n");
      out.write("}\n");
      out.write(".info, .success, .warning, .error, .validation {\n");
      out.write("border: 1px solid;\n");
      out.write("margin: 10px 0px;\n");
      out.write("padding:15px 10px 15px 50px;\n");
      out.write("background-repeat: no-repeat;\n");
      out.write("background-position: 10px center;\n");
      out.write("}\n");
      out.write(".cwhite{\n");
      out.write("color: white;\n");
      out.write("}\n");
      out.write(".info {\n");
      out.write("color: #00529B;\n");
      out.write("background-color: #BDE5F8;\n");
      out.write("background-image: url('https://cdn4.iconfinder.com/data/icons/32x32-free-design-icons/32/Info.png');\n");
      out.write("}\n");
      out.write(".success {\n");
      out.write("color: #4F8A10;\n");
      out.write("background-color: #DFF2BF;\n");
      out.write("background-image:url('https://cdn4.iconfinder.com/data/icons/32x32-free-design-icons/32/Ok.png');\n");
      out.write("}\n");
      out.write(".warning {\n");
      out.write("color: #9F6000;\n");
      out.write("background-color: #FEEFB3;\n");
      out.write("background-image: url('');\n");
      out.write("}\n");
      out.write(".error {\n");
      out.write("color: #D8000C;\n");
      out.write("background-color: #FFBABA;\n");
      out.write("background-image: url('https://cdn4.iconfinder.com/data/icons/32x32-free-design-icons/32/Cancel.png');\n");
      out.write("}\n");
      out.write("\n");
      out.write(".div-table{\n");
      out.write("  display:table;         \n");
      out.write("  width:1000px;;         \n");
      out.write("  /* background-color:#eee;  */        \n");
      out.write("  border:1px solid  #666666;         \n");
      out.write("  border-spacing:5px;/*cellspacing:poor IE support for  this*/\n");
      out.write("  margin-top:10px;\n");
      out.write("}\n");
      out.write(".div-table-row{\n");
      out.write("  display:table-row;\n");
      out.write("  width:auto;\n");
      out.write("  clear:both;\n");
      out.write("}\n");
      out.write(".div-table-col{\n");
      out.write("  float:left;/*fix for  buggy browsers*/\n");
      out.write("  display:table-column;         \n");
      out.write("  width:300px;         \n");
      out.write("  /* background-color:#ccc; */  \n");
      out.write("}\n");
      out.write("    body{\n");
      out.write(" /*  background:#567; */\n");
      out.write("  font-family:'Open Sans',sans-serif;\n");
      out.write("}\n");
      out.write("\n");
      out.write("tr.spaceUnder > td\n");
      out.write("{\n");
      out.write("  padding-bottom:2em;\n");
      out.write("}\n");
      out.write("\n");
      out.write("tr.spaceUpper > td\n");
      out.write("{\n");
      out.write("  padding-top: 2em;\n");
      out.write("}\n");
      out.write(".tabhead{\n");
      out.write("font-size: 1.1em;\n");
      out.write("    text-align: left;\n");
      out.write("    padding-top: 5px;\n");
      out.write("    padding-bottom: 10px;\n");
      out.write("    font-weight:bold;\n");
      out.write("    background-color:#DCDCDC;\n");
      out.write("    color: Black;\n");
      out.write("    margin-left:10px;\n");
      out.write("}\n");
      out.write(".form{\n");
      out.write("    padding:20px\n");
      out.write("}\n");
      out.write(".cancel{\n");
      out.write("    \n");
      out.write("    padding:20px;\n");
      out.write("}\n");
      out.write("html, body{\n");
      out.write("    background-color: white;\n");
      out.write("}\n");
      out.write("  </style>\n");
      out.write("    <title>{{testcaseset}}</title>  \n");
      out.write("     <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css\">\n");
      out.write("     <!-- <link rel=\"stylesheet\" href=\"app.css\"> -->\n");
      out.write("  </head>\n");
      out.write("  <body ng-app=\"plunker\">\n");
      out.write("     <!--  <div ng-show=\"isActive('testcase')\"> -->\n");
      out.write("    <div ng-controller=\"TestcaseListCtrl\" data-ng-init=\"init('");
      out.print(session.getAttribute("name"));
      out.write("')\">\n");
      out.write("    <b>{{testcaseset}}</b> </br>\n");
      out.write("    </br>\n");
      out.write("    <div ng-show=\"!showcheck\">\n");
      out.write("   <table class=\"table table-bordered table-striped\">\n");
      out.write("        <div class=\"cancel\">\n");
      out.write("     <div ng-show=\"loader1.loading\" class=\"info\">App is being tested. Please wait for results.</div>\n");
      out.write("</div>\n");
      out.write("    <thead>\n");
      out.write("      <tr>\n");
      out.write("        <td>\n");
      out.write("         S.No.\n");
      out.write("        </td>\n");
      out.write("        <td>\n");
      out.write("          <a href=\"#\" ng-click=\"sortType = 'device'; sortReverse = !sortReverse\">\n");
      out.write("            Device ID\n");
      out.write("            <span ng-show=\"sortType == 'device' && !sortReverse\"><i class=\"fa fa-caret-down\"></i>\n");
      out.write("            </span>\n");
      out.write("            <span ng-show=\"sortType == 'device' && sortReverse\" class=\"fa fa-caret-up\"></span>\n");
      out.write("          </a>\n");
      out.write("        </td>\n");
      out.write("        <td>\n");
      out.write("          <a href=\"#\" ng-click=\"sortType = 'model'; sortReverse = !sortReverse\">\n");
      out.write("           Status\n");
      out.write("            <span ng-show=\"sortType == 'model' && !sortReverse\" class=\"fa fa-caret-down\"></span>\n");
      out.write("            <span ng-show=\"sortType == 'model' && sortReverse\" class=\"fa fa-caret-up\"></span>\n");
      out.write("          </a>\n");
      out.write("        </td>\n");
      out.write("        <td>\n");
      out.write("          <a href=\"#\" ng-click=\"sortType = 'brand'; sortReverse = !sortReverse\">\n");
      out.write("          Creation Date and Time taken\n");
      out.write("            <span ng-show=\"sortType == 'brand' && !sortReverse\" class=\"fa fa-caret-down\"></span>\n");
      out.write("            <span ng-show=\"sortType == 'brand' && sortReverse\" class=\"fa fa-caret-up\"></span>\n");
      out.write("          </a>\n");
      out.write("        </td>\n");
      out.write("        <td>\n");
      out.write("          <a href=\"#\" ng-click=\"sortType = 'version'; sortReverse = !sortReverse\">\n");
      out.write("          Log\n");
      out.write("            <span ng-show=\"sortType == 'version' && !sortReverse\" class=\"fa fa-caret-down\"></span>\n");
      out.write("            <span ng-show=\"sortType == 'version' && sortReverse\" class=\"fa fa-caret-up\"></span>\n");
      out.write("          </a>\n");
      out.write("        </td>\n");
      out.write("      </tr>\n");
      out.write("    </thead>\n");
      out.write("     <tbody>\n");
      out.write("      <tr ng-repeat=\"device in devices | orderBy:sortType:sortReverse | filter:searchDevice\">\n");
      out.write("       <td>  <input type=\"checkbox\" ng-model=\"myTestcases.selected[$index]\" ng-true-value=\"{{device.device}}\" ng-false-value=\"\"/></td>\n");
      out.write("        <td> <a ng-click=\"showdetails(device.device)\" class=\" btn glyphicon glyphicon-phone\">{{ device.device }} {{device.brand}}</a></td>\n");
      out.write("        <td><!-- {{ device.status }} -->\n");
      out.write("               <div class=\"cancel\">\n");
      out.write("        <button ng-show=\"loader1.loading\" class=\"btn btn-success\">Loading...\n");
      out.write("        <i class=\"fa fa-spinner fa-spin\"></i>\n");
      out.write("        </button>\n");
      out.write("          <div ng-show=\"device.status=='Pass'  || device.status == '' \">\n");
      out.write("          <div class=\"div-table-row\">\n");
      out.write("     <div ng-show=\"status1.loading\" class=\"success\">Pass</div>\n");
      out.write("     </div>\n");
      out.write("</div>\n");
      out.write("   <div ng-show=\"device.status=='Fail' || device.status=='FAIL' \">\n");
      out.write("   <div class=\"div-table-row\">\n");
      out.write("     <div ng-show=\"status1.loading\" class=\"error\" >{{device.errormsg}}</div>\n");
      out.write("     </div>\n");
      out.write("</div>\n");
      out.write("       \n");
      out.write("</div>\n");
      out.write("        </td>\n");
      out.write("        <td>          <div class=\"cancel\">\n");
      out.write("                 <div ng-show=\"status1.loading\">{{device.date}}, {{device.time}} ms</div>\n");
      out.write("     </div></td>\n");
      out.write("        <td><a href ng-click=\"getlogfile(device.logpath)\">log</a></td>\n");
      out.write("      </tr>\n");
      out.write("    </tbody> \n");
      out.write("\n");
      out.write("  </table>\n");
      out.write("  </div>\n");
      out.write("    <div ng-show=\"showcheck\">\n");
      out.write("   <table class=\"table table-bordered table-striped\">\n");
      out.write("        <div class=\"cancel\">\n");
      out.write("     <div ng-show=\"loader1.loading\" class=\"info\">App is being tested. Please wait for results.</div>\n");
      out.write("</div>\n");
      out.write("    <thead>\n");
      out.write("      <tr>\n");
      out.write("     <!--    <td>\n");
      out.write("         S.No.\n");
      out.write("        </td> -->\n");
      out.write("        <td>\n");
      out.write("          <a href=\"#\" ng-click=\"sortType = 'device'; sortReverse = !sortReverse\">\n");
      out.write("            Device ID\n");
      out.write("            <span ng-show=\"sortType == 'device' && !sortReverse\"><i class=\"fa fa-caret-down\"></i>\n");
      out.write("            </span>\n");
      out.write("            <span ng-show=\"sortType == 'device' && sortReverse\" class=\"fa fa-caret-up\"></span>\n");
      out.write("          </a>\n");
      out.write("        </td>\n");
      out.write("        <td>\n");
      out.write("          <a href=\"#\" ng-click=\"sortType = 'model'; sortReverse = !sortReverse\">\n");
      out.write("           Status\n");
      out.write("            <span ng-show=\"sortType == 'model' && !sortReverse\" class=\"fa fa-caret-down\"></span>\n");
      out.write("            <span ng-show=\"sortType == 'model' && sortReverse\" class=\"fa fa-caret-up\"></span>\n");
      out.write("          </a>\n");
      out.write("        </td>\n");
      out.write("        <td>\n");
      out.write("          <a href=\"#\" ng-click=\"sortType = 'brand'; sortReverse = !sortReverse\">\n");
      out.write("          Creation Date and Time taken\n");
      out.write("            <span ng-show=\"sortType == 'brand' && !sortReverse\" class=\"fa fa-caret-down\"></span>\n");
      out.write("            <span ng-show=\"sortType == 'brand' && sortReverse\" class=\"fa fa-caret-up\"></span>\n");
      out.write("          </a>\n");
      out.write("        </td>\n");
      out.write("        <td>\n");
      out.write("          <a href=\"#\" ng-click=\"sortType = 'version'; sortReverse = !sortReverse\">\n");
      out.write("          Log\n");
      out.write("            <span ng-show=\"sortType == 'version' && !sortReverse\" class=\"fa fa-caret-down\"></span>\n");
      out.write("            <span ng-show=\"sortType == 'version' && sortReverse\" class=\"fa fa-caret-up\"></span>\n");
      out.write("          </a>\n");
      out.write("        </td>\n");
      out.write("      </tr>\n");
      out.write("    </thead>\n");
      out.write("     <tbody>\n");
      out.write("      <tr ng-repeat=\"device in testlist | orderBy:sortType:sortReverse | filter:searchDevice\">\n");
      out.write("       <!-- <td> --> <!--  <input type=\"checkbox\" ng-model=\"myTestcases.selected[$index]\" ng-true-value=\"{{device.device}}\" ng-false-value=\"\"/> --><!-- </td> -->\n");
      out.write("        <td> <a ng-click=\"showdetails(device.device)\" class=\" btn glyphicon glyphicon-phone\">{{ device.device }} {{device.brand}}</a></td>\n");
      out.write("        <td><!-- {{ device.status }} -->\n");
      out.write("               <div class=\"cancel\">\n");
      out.write("        <button ng-show=\"loader1.loading\" class=\"btn btn-success\">Loading...\n");
      out.write("        <i class=\"fa fa-spinner fa-spin\"></i>\n");
      out.write("        </button>\n");
      out.write("          <div ng-show=\"device.status=='Pass'  || device.status == '' \">\n");
      out.write("          <div class=\"div-table-row\">\n");
      out.write("     <div ng-show=\"status1.loading\" class=\"success\">Pass</div>\n");
      out.write("     </div>\n");
      out.write("</div>\n");
      out.write("   <div ng-show=\"device.status=='Fail' || device.status=='FAIL' \">\n");
      out.write("   <div class=\"div-table-row\">\n");
      out.write("     <div ng-show=\"status1.loading\" class=\"error\" >{{device.errormsg}}</div>\n");
      out.write("     </div>\n");
      out.write("</div>\n");
      out.write("       \n");
      out.write("</div>\n");
      out.write("        </td>\n");
      out.write("        <td>          <div class=\"cancel\">\n");
      out.write("                 <div ng-show=\"status1.loading\">{{device.date}}, {{device.time}} ms</div>\n");
      out.write("     </div></td>\n");
      out.write("        <td><a href ng-click=\"getlogfile(device.logpath)\">log</a></td>\n");
      out.write("      </tr>\n");
      out.write("    </tbody> \n");
      out.write("\n");
      out.write("  </table>\n");
      out.write("  </div>\n");
      out.write("  <div ng-show=\"showcheck\">\n");
      out.write("   <div align=\"Right\">\n");
      out.write("        <a ng-click=\"testsub(testcaseset,testlist);\" class=\" btn glyphicon glyphicon-expand btn-primary\">Review and run test case</a>\n");
      out.write("    &nbsp; &nbsp;&nbsp;  <!--  <a  class=\" btn glyphicon glyphicon-remove-sign btn-danger\"> Cancel</a> -->\n");
      out.write("       </div>\n");
      out.write("       </div>\n");
      out.write("         <div ng-show=\"!showcheck\" align=\"Right\" >\n");
      out.write("            <div class=\"row\" style=\"font-family:calibri;\">\n");
      out.write("                       <button type=\"button\" ng-click=\"submitform(myTestcases.selected,devices);showcheck=!showcheck;\"><b>Next</b></button>\n");
      out.write("                      </div>\n");
      out.write("                       </div>\n");
      out.write("    </div>\n");
      out.write(" \n");
      out.write("    </div>\n");
      out.write("       \n");
      out.write("      <script src=\"https://ajax.googleapis.com/ajax/libs/angularjs/1.2.8/angular.js\">\n");
      out.write("      </script>  \n");
      out.write("   \n");
      out.write("  </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
