/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2016-01-27 00:58:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class TestcaseMapping_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\n");
      out.write("<html ng-app=\"plunker\">\n");
      out.write("  <head>\n");
      out.write("  <script data-require=\"angular.js@1.2.8\" data-semver=\"1.2.8\" src=\"https://code.angularjs.org/1.2.8/angular.js\"></script>\n");
      out.write("    <link data-require=\"bootstrap@*\" data-semver=\"3.2.0\" rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.css\" />\n");
      out.write("    <link data-require=\"bootstrap-css@~3.1.1\" data-semver=\"3.1.1\" rel=\"stylesheet\" href=\"//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css\" />\n");
      out.write("    <link data-require=\"font-awesome@*\" data-semver=\"4.2.0\" rel=\"stylesheet\" href=\"//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.2.0/css/font-awesome.css\" />\n");
      out.write("    <script data-require=\"ui-bootstrap@*\" data-semver=\"0.11.0\" src=\"http://angular-ui.github.io/bootstrap/ui-bootstrap-tpls-0.11.0.min.js\"></script>\n");
      out.write("    <script src=\"example.js\"></script>\n");
      out.write("     <script src=\"moment.js\"></script>\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/styles.css\"> \n");
      out.write("    <link rel=\"stylesheet\" href=\"newcss.css\"> \n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("    var deviceId;\n");
      out.write("    var processed_json = new Array(); \n");
      out.write("    var processed_json1 = new Array();  \n");
      out.write("    $( document ).ready(function() {\n");
      out.write("    \tvar processed_json = new Array();\n");
      out.write("   \t var processed_json1 = new Array(); \n");
      out.write("   \t var url = window.location.href.split('/');\n");
      out.write("  \t  var baseUrl = url[0] + '//' + url[2]+\"/\"+url[3]+\"/\";\n");
      out.write("  \t // alert(\"Base Url:\"+baseUrl);\n");
      out.write("  \tvar pathname = window.location.pathname; // Returns path only\n");
      out.write("  \tvar url1      = window.location.href; \n");
      out.write("  var testcase = url1.substr(url1.indexOf(\"=\") + 1);\n");
      out.write("  </script>\n");
      out.write("    \n");
      out.write("<style>\n");
      out.write("  body{\n");
      out.write("  background-color:white;\n");
      out.write("  }\n");
      out.write(" \n");
      out.write("\n");
      out.write("  body{\n");
      out.write("font-family:Arial, Helvetica, sans-serif; \n");
      out.write("font-size:17px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("    body{\n");
      out.write(" /*  background:#567; */\n");
      out.write("  font-family:'Open Sans',sans-serif;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write(".form{\n");
      out.write("    padding:20px\n");
      out.write("}\n");
      out.write("\n");
      out.write("html, body{\n");
      out.write("    background-color: white;\n");
      out.write("}\n");
      out.write("    </style>\n");
      out.write("    \n");
      out.write("    </head>\n");
      out.write("    \n");
      out.write("    <body>\n");
      out.write("    <div class=\"page\"ng-controller=\"DevicesCtrl as ctrl\" ng-init=\"init()\">\n");
      out.write("    <!-- <div ng-repeat=\"device in devices\">\n");
      out.write(" \n");
      out.write("    </div> -->\n");
      out.write("    <form>\n");
      out.write("    <div class=\"form-group\">\n");
      out.write("      <div class=\"input-group\">\n");
      out.write("        <div class=\"input-group-addon\"><i class=\"fa fa-search\"></i></div>\n");
      out.write("        <input type=\"text\" class=\"form-control\" placeholder=\"Search device\" ng-model=\"searchDevice\">\n");
      out.write("      </div>      \n");
      out.write("    </div>\n");
      out.write("  </form>\n");
      out.write("  <div ng-show=\"!showcheck\">\n");
      out.write("  <table class=\"table table-bordered table-striped\">\n");
      out.write("    \n");
      out.write("    <thead>\n");
      out.write("      <tr>\n");
      out.write("        <td>\n");
      out.write("          Sno.\n");
      out.write("        </td>\n");
      out.write("        <td>\n");
      out.write("          <a href=\"#\" ng-click=\"sortType = 'device'; sortReverse = !sortReverse\">\n");
      out.write("            Device Name \n");
      out.write("            <span ng-show=\"sortType == 'device' && !sortReverse\"><i class=\"fa fa-caret-down\"></i>\n");
      out.write("            </span>\n");
      out.write("            <span ng-show=\"sortType == 'device' && sortReverse\" class=\"fa fa-caret-up\"></span>\n");
      out.write("          </a>\n");
      out.write("        </td>\n");
      out.write("        <td>\n");
      out.write("          <a href=\"#\" ng-click=\"sortType = 'model'; sortReverse = !sortReverse\">\n");
      out.write("           Device Model \n");
      out.write("            <span ng-show=\"sortType == 'model' && !sortReverse\" class=\"fa fa-caret-down\"></span>\n");
      out.write("            <span ng-show=\"sortType == 'model' && sortReverse\" class=\"fa fa-caret-up\"></span>\n");
      out.write("          </a>\n");
      out.write("        </td>\n");
      out.write("        <td>\n");
      out.write("          <a href=\"#\" ng-click=\"sortType = 'brand'; sortReverse = !sortReverse\">\n");
      out.write("          Brand\n");
      out.write("            <span ng-show=\"sortType == 'brand' && !sortReverse\" class=\"fa fa-caret-down\"></span>\n");
      out.write("            <span ng-show=\"sortType == 'brand' && sortReverse\" class=\"fa fa-caret-up\"></span>\n");
      out.write("          </a>\n");
      out.write("        </td>\n");
      out.write("        <td>\n");
      out.write("          <a href=\"#\" ng-click=\"sortType = 'version'; sortReverse = !sortReverse\">\n");
      out.write("          Version \n");
      out.write("            <span ng-show=\"sortType == 'version' && !sortReverse\" class=\"fa fa-caret-down\"></span>\n");
      out.write("            <span ng-show=\"sortType == 'version' && sortReverse\" class=\"fa fa-caret-up\"></span>\n");
      out.write("          </a>\n");
      out.write("        </td>\n");
      out.write("      </tr>\n");
      out.write("    </thead>\n");
      out.write("    \n");
      out.write("    <tbody>\n");
      out.write("      <tr ng-repeat=\"roll in devices | orderBy:sortType:sortReverse | filter:searchDevice\">\n");
      out.write("      <td>  <input type=\"checkbox\" ng-model=\"myTestcases.selected[$index]\" ng-true-value=\"{{roll.device}}\" ng-false-value=\"\"/></td>\n");
      out.write("        <td>{{ roll.device }}</td>\n");
      out.write("     <!--    <td ng-show=\"showcheck\"> <select name=\"group\" data-ng-options=\"s.testcase for s in testcases\" data-ng-model=\"group\"  ng-change=\"change(group.id)\" required></select></td> -->\n");
      out.write("        <td>{{ roll.model }}</td>\n");
      out.write("        <td>{{ roll.brand }}</td>\n");
      out.write("        <td>{{ roll.version }}</td>\n");
      out.write("      </tr>\n");
      out.write("      <!--  {{myTestcases.selected}} -->\n");
      out.write("    </tbody>\n");
      out.write("    \n");
      out.write("  </table>\n");
      out.write("  </div>\n");
      out.write("  <div ng-show=\"showcheck\">\n");
      out.write("  <table class=\"table table-bordered table-striped\">\n");
      out.write("    \n");
      out.write("    <thead>\n");
      out.write("      <tr>\n");
      out.write("      <!--   <td>\n");
      out.write("          Sno.\n");
      out.write("        </td> -->\n");
      out.write("        <td>\n");
      out.write("          <a href=\"#\" ng-click=\"sortType = 'device'; sortReverse = !sortReverse\">\n");
      out.write("            Device Name \n");
      out.write("            <span ng-show=\"sortType == 'device' && !sortReverse\"><i class=\"fa fa-caret-down\"></i>\n");
      out.write("            </span>\n");
      out.write("            <span ng-show=\"sortType == 'device' && sortReverse\" class=\"fa fa-caret-up\"></span>\n");
      out.write("          </a>\n");
      out.write("        </td>\n");
      out.write("         <td>\n");
      out.write("          <a href=\"#\" ng-click=\"sortType = 'testcase'; sortReverse = !sortReverse\">\n");
      out.write("            Testcase Name \n");
      out.write("            <span ng-show=\"sortType == 'testcase' && !sortReverse\"><i class=\"fa fa-caret-down\"></i>\n");
      out.write("            </span>\n");
      out.write("            <span ng-show=\"sortType == 'testcase' && sortReverse\" class=\"fa fa-caret-up\"></span>\n");
      out.write("          </a>\n");
      out.write("        </td>\n");
      out.write("        <td>\n");
      out.write("          <a href=\"#\" ng-click=\"sortType = 'model'; sortReverse = !sortReverse\">\n");
      out.write("           Device Model \n");
      out.write("            <span ng-show=\"sortType == 'model' && !sortReverse\" class=\"fa fa-caret-down\"></span>\n");
      out.write("            <span ng-show=\"sortType == 'model' && sortReverse\" class=\"fa fa-caret-up\"></span>\n");
      out.write("          </a>\n");
      out.write("        </td>\n");
      out.write("        <td>\n");
      out.write("          <a href=\"#\" ng-click=\"sortType = 'brand'; sortReverse = !sortReverse\">\n");
      out.write("          Brand\n");
      out.write("            <span ng-show=\"sortType == 'brand' && !sortReverse\" class=\"fa fa-caret-down\"></span>\n");
      out.write("            <span ng-show=\"sortType == 'brand' && sortReverse\" class=\"fa fa-caret-up\"></span>\n");
      out.write("          </a>\n");
      out.write("        </td>\n");
      out.write("        <td>\n");
      out.write("          <a href=\"#\" ng-click=\"sortType = 'version'; sortReverse = !sortReverse\">\n");
      out.write("          Version \n");
      out.write("            <span ng-show=\"sortType == 'version' && !sortReverse\" class=\"fa fa-caret-down\"></span>\n");
      out.write("            <span ng-show=\"sortType == 'version' && sortReverse\" class=\"fa fa-caret-up\"></span>\n");
      out.write("          </a>\n");
      out.write("        </td>\n");
      out.write("      </tr>\n");
      out.write("    </thead>\n");
      out.write("    \n");
      out.write("    <tbody>\n");
      out.write("      <tr ng-repeat=\"roll in testlist | orderBy:sortType:sortReverse | filter:searchDevice\">\n");
      out.write("        <td>{{ roll.device }}</td>\n");
      out.write("        <td></td>\n");
      out.write("        <!-- <td> <select name=\"testcase\" data-ng-options=\"s.testcase for s in testcases\" data-ng-model=\"myTestcases1.selected[s.testcase]\" required></select></td> -->\n");
      out.write("        <td>{{ roll.model }}</td>\n");
      out.write("        <td>{{ roll.brand }}</td>\n");
      out.write("        <td>{{ roll.version }}</td>\n");
      out.write("      </tr>\n");
      out.write("   <!--    {{myTestcases.selected}} -->\n");
      out.write("    </tbody>\n");
      out.write("    \n");
      out.write("  </table>\n");
      out.write("  \n");
      out.write("    <div style=\"margin-left:800px\" >\n");
      out.write("            <div class=\"row\" style=\"font-family:calibri;\">\n");
      out.write("                       <button type=\"button\" ng-click=\"submitTests(myTestcases1.selected,devices);showcheck=!showcheck;\"><b>Review and Run Test Case</b></button>\n");
      out.write("               </div>\n");
      out.write("                       </div>\n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("\n");
      out.write("                        \n");
      out.write("   <div ng-show=\"!showcheck\" style=\"margin-left:900px\" >\n");
      out.write("            <div class=\"row\" style=\"font-family:calibri;\">\n");
      out.write("                       <button type=\"button\" ng-click=\"submitform(myTestcases.selected,devices);showcheck=!showcheck;\"><b>Next</b></button>\n");
      out.write("                      </div>\n");
      out.write("                       </div>\n");
      out.write("</div>\n");
      out.write(" \n");
      out.write("    </body>\n");
      out.write("    \n");
      out.write("    </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
