// Generated by CoffeeScript 1.4.0
(function() {
  var Pages,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.App = {
    loadQueue: []
  };

  Pages = (function(_super) {

    __extends(Pages, _super);

    function Pages() {
      this.confirmDeletion = __bind(this.confirmDeletion, this);

      this.deleteFiddle = __bind(this.deleteFiddle, this);

      this.toggleShadow = __bind(this.toggleShadow, this);
      this.csrftoken = Cookie.read("csrftoken");
      this.elements = {
        formTips: document.getElements(".formTip"),
        document: document.body,
        window: window,
        shadow: document.id("shadow")
      };
      this.elements.formTips.twipsy({
        trigger: "focus",
        offset: 5,
        animate: false,
        placement: "right"
      });
      this.events = {
        document: {
          "click:relay(.delete a)": this.confirmDeletion
        },
        window: {
          "scroll": this.toggleShadow
        }
      };
      this.setupEvents(this.elements, this.events);
    }

    Pages.prototype.toggleShadow = function() {
      var element, scrollHeight;
      if (this.elements.shadow) {
        element = document.body;
        scrollHeight = element.getScroll().y;
        if (scrollHeight <= 10) {
          return this.elements.shadow.setStyle("opacity", scrollHeight / 10);
        }
      }
    };

    Pages.prototype.deleteFiddle = function(response, element) {
      var fiddle, hasMany, request,
        _this = this;
      fiddle = element.getParent(".item");
      hasMany = response.shells > 1;
      request = new Request.JSON({
        url: response.delete_url,
        method: "delete",
        headers: {
          "X-CSRFToken": this.csrftoken
        },
        onRequest: function() {
          return fiddle.setStyle("opacity", 0.5);
        },
        onComplete: function(response) {
          return fiddle.dissolve();
        }
      });
      if (confirm("Are you sure you want to delete " + response.title + (hasMany ? " and " + response.shells + " revision" + (hasMany ? "s" : void 0) + "?" : "."))) {
        return request.send();
      }
    };

    Pages.prototype.confirmDeletion = function(event, element) {
      var request,
        _this = this;
      if (event != null) {
        event.stop();
      }
      request = new Request.JSON({
        url: element.get("href"),
        headers: {
          "X-CSRFToken": this.csrftoken
        },
        onComplete: function(response) {
          return _this.deleteFiddle(response, element);
        }
      });
      return request.send();
    };

    return Pages;

  })(Helpers);

  window.App.loadQueue.push(function() {
    return new Pages();
  });

}).call(this);
